### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by langdonholmes** [learlab/strapi#38]
It would be really nice to import the CSS from the main iTELL app directly. This would allow us to easily and effectively display elements as they would appear in iTELL.

iTELL uses Tailwind, which I don't know much about, but I did find a discussion of people adding Tailwind to Strapi: https://forum.strapi.io/t/strapi-v4-plugin-and-tailwindcss/32893

On the other hand, it might be simpler to get some kind of CSS export from iTELL's Tailwind styles, but I'm not sure if that's possible.

**Comment by langdonholmes** [comment]
This approach is a bit more manual, but might be good enough since we don't need to be perfect about this.

![image](https://github.com/user-attachments/assets/ec0316eb-a4fd-4114-834d-35c30d392e1d)

I copied the rendered HTML from a live iTELL deployment and entered it into a [Tailwind-to-CSS tool](https://tailwind-to-css.vercel.app/).

It took some manual manipulation of the CSS styles, but I think something like this would be close enough.

```css
.ck section.Callout{
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='size-4'%3E%3Ccircle cx='12' cy='12' r='10'%3E%3C/circle%3E%3Cpath d='M12 16v-4'%3E%3C/path%3E%3Cpath d='M12 8h.01'%3E%3C/path%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position-x: 2px;
  background-position-y: 2px;
  padding: 0.5rem; 
  padding-left: 1.8rem;
  border-radius: 0.5rem; 
  background-color: hsl(214 95% 93%);
}

.ck section.Callout > p {
  margin-bottom: 0.25rem; 
  font-weight: 500; 
  line-height: 1; 
}
```
